### PR TITLE
Fix import

### PR DESCRIPTION
**Pull request by vya**

### CODE REVIEW

**Comment by mlynch** [comment]
Thanks. Can you explain the reasoning behind this change? Changing the imports could break things so I want to know what your thought process is.

**Comment by vya** [comment]
Hi. This change fixes a problem with imports of modules, described in the issue #18.

**Comment by ErvalhouS** [comment]
This branch breaks `this.storage.get` and `this.storage.set` methods on my Ionic2 project. Issue with LocalForage persists on version 1.1.8

**Comment by thgreasi** [comment]
@vya What typescript version are you using? Are you using `allowSyntheticDefaultImports` in your `tsconfig` ([also noted in localforage's README](https://github.com/localForage/localForage#typescript))?
@ErvalhouS I can confirm that such a change would result runtime errors.

**Comment by danielsogl** [comment]
@vya I think you can close this PR

**Pull request closed without merging**
