### PR TITLE
Update angular package to use Ivy

### LINKED ISSUE #249: Ivy distibution for angular 13
When I build my angular+ionic app, the `ionic-storage` package is the last view engine library:
```
ng run app:serve --host=localhost --port=8101
[ng] - Generating browser application bundles (phase: setup)...
[ng] Processing legacy "View Engine" libraries:
[ng] - @ionic/storage-angular [es2015/esm2015] (git+https://github.com/ionic-team/ionic-storage.git)
[ng] Encourage the library authors to publish an Ivy distribution.
```

### LINKED ISSUE #250: Error when running an Ionic 5 project using @ionic/storage-angular@3.x
Hi, I have set up @ionic/storage-angular according to the documentation available and yet I am getting the error shown in the screenshot I am attaching in the provideStorage function exported from the @ionic/storage-angular project.

Am I missing something? Or is there an issue with the library? I do have to say that using `this` in the provideStorage function seems at least a bit suspicious to me, what instance is this function attached to supposedly?

Thanks.

https://github.com/ionic-team/ionic-storage/blob/ff9183c6e903798da833e372a8d6c037df21f005/angular/src/index.ts#L40

image

### LINKED ISSUE #251: Problem compiling Ionic 5/Capacitor 3 project using AOT
Hi,

I am having an issue building a project built with Ionic 5/Capacitor 3 and using the ionic-storage package when AOT is enabled. The build process fails with this error:
```
ERROR in app/app.module.ts(52,50): Error during template compile of 'AppModule'
  Only initialized variables and constants can be referenced in decorators because the value of this variable is n
eeded by the template compiler in 'Drivers'                                                                      
    'Drivers' is not initialized at ../@ionic/storage/dist/esm/index.ts(2,22).

[ERROR] An error occurred while running subprocess ng.
```
Is there something I'm doing wrong? I have followed the setup steps detailed in the configuration?
Any chance it is related in any way to https://github.com/ionic-team/ionic-storage/issues/228 and the fact that Drivers is @hidden?

Thanks

### LINKED ISSUE #256: Module '"@ionic/storage-angular"' has no exported member 'Drivers'
When using the angular library `@ionic/storage-angular`, we are also required to install the other library `@ionic/storage` just to access the `Driver `.

### PR DESCRIPTION
**Pull request by Theaninova**
Fixes #249 
Should fix #256, fix #251, fix #250

* Update to Angular 15
* Replaced TSLint with ESLint + Prettier
* Updated various dependencies

### CODE REVIEW

**Comment by Theaninova** [comment]
As a temporary workaround until a new release is made, you can copy [this file](https://github.com/ionic-team/ionic-storage/blob/152c32dd965825601be97cabc0cc713ac1373fb3/angular/src/index.ts) into your project and replace the `@ionic/storage-angular` with `@ionic/storage`

**Comment by dnietodev** [comment]
Hello, im highly interested in this PR to be merged, when can we expect to have a new version with this fixes?
Thanks!

**Comment by mlynch** [comment]
Thanks for the PR. How does this impact older versions of Angular? I'm not up to speed on the latest module format.

**Comment by Theaninova** [comment]
> Thanks for the PR. How does this impact people on older versions of Angular? I'm not up to speed on the latest module format. I'm assuming it'll require a major version release?

Good question, I don't know actually, but I think it will not work with Angular <9 or anyone who has chosen to opt-out of Ivy.

I think it's worth mentioning that with Angular 9 (first version with Ivy by default) being released in early 2020, it has been out of LTS for 1.5 years already, and view engine has been deprecated since v12 which is also out of LTS.

**Comment by mlynch** [comment]
Okay published `@ionic/storage-angular` `4.0.0-next.0@next` if someone wants to test that and see how it works

**Comment by dtarnawsky** [comment]
If you test with https://github.com/ionic-team/ionifits by installing this version:
`npm install @ionic/storage-angular@4.0.0-next.0`

You get build errors:
`Error: src/app/services/storage.service.ts:5:25 - error TS2307: Cannot find module '@ionic/storage-angular' or its corresponding type declarations.`

**Comment by mlynch** [comment]
Okay `@ionic/storage-angular@4.0.0-next.1@next` seems to be working locally for me. Will wait for more testers before cutting a 4.0 release

**Comment by WolfWalter** [comment]
Hi,
ich get the same error as @dtarnawsky with`@ionic/storage-angular@4.0.0-next.1@next`. 

```bash
./src/app/shared/services/persistent-storage.service.ts:2:0-49 - Error: Module not found: Error: Can't resolve '@ionic/storage-angular' in 'xxx/app/src/app/shared/services'

./src/main.ts:28:0-60 - Error: Module not found: Error: Can't resolve '@ionic/storage-angular' in 'xxx/app/src'

Error: src/app/shared/services/persistent-storage.service.ts:2:25 - error TS2307: Cannot find module '@ionic/storage-angular' or its corresponding type declarations.

2 import { Storage } from '@ionic/storage-angular';
                          ~~~~~~~~~~~~~~~~~~~~~~~~


Error: src/main.ts:28:36 - error TS2307: Cannot find module '@ionic/storage-angular' or its corresponding type declarations.

28 import { IonicStorageModule } from '@ionic/storage-angular';
```

**Comment by magyargergo** [comment]
> Hi, ich get the same error as @dtarnawsky with`@ionic/storage-angular@4.0.0-next.1@next`.
> 
> ```shell
> ./src/app/shared/services/persistent-storage.service.ts:2:0-49 - Error: Module not found: Error: Can't resolve '@ionic/storage-angular' in 'xxx/app/src/app/shared/services'
> 
> ./src/main.ts:28:0-60 - Error: Module not found: Error: Can't resolve '@ionic/storage-angular' in 'xxx/app/src'
> 
> Error: src/app/shared/services/persistent-storage.service.ts:2:25 - error TS2307: Cannot find module '@ionic/storage-angular' or its corresponding type declarations.
> 
> 2 import { Storage } from '@ionic/storage-angular';
>                           ~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: src/main.ts:28:36 - error TS2307: Cannot find module '@ionic/storage-angular' or its corresponding type declarations.
> 
> 28 import { IonicStorageModule } from '@ionic/storage-angular';
> ```

I tried to upgrade to `@ionic/storage-angular@4.0.0-next.1@next` as well and the respective `node_modules` folder was not having source files.

What else do we need to release 4.0? cc @mlynch

**Comment by Theaninova** [comment]
Hmm, I'll take a look today at what went wrong

**Comment by boradakash** [comment]
Any update on this?
I also tried to upgrade to @ionic/storage-angular@4.0.0-next.1@next and the node_modules folder is not having source files.
and it returns following error:
image

**Comment by mlynch** [comment]
Okay I've fixed the package and republished it and can verify the dist files are correctly bundled, and I'm still getting this error now, so I'm going to revert this PR until we can figure out what's not working. I'm not experienced enough in Angular to do the work on this so if someone else was able to get this working end-to-end we can take another look at it, thanks.

**Pull request merged**
