### PR TITLE
fix(storage): better detect ssr envs

### PR DESCRIPTION
**Pull request by mhartington**
Change the way that ssr/node envs are detected

### CODE REVIEW

**Comment by pookdeveloper** [comment]
@mhartington what is the new parameter "platformId" ?
Before I used like this now that I have to pass in the new parameter ? Thanks
    this._storage = new Storage({
      name: this.NAME,
      storeName: this.TABLE_NAME,
      driverOrder: tihs.DRIVERS
    });

**Comment by mhartington** [comment]
Since this is an angular module, you would use Angular's ngModules to include Ionic Storage.


https://github.com/ionic-team/ionic-storage#usage

Your way is not supported.

**Comment by pookdeveloper** [comment]
I want to create dynamic storage with diferent drivers, so i call IonocModule without .forroot and i create the instance in my service, so I cant do that ? Thanks @mhartington

**Comment by mhartington** [comment]
That defeats the point of this package. If you want that, then just use localforage directly.

If there is any real issue, please open a new issue instead of commenting on PRs.

**Pull request merged**
