### PR TITLE
fix(storage): add a generic type to ModuleWithProviders usage

### LINKED ISSUE #187: Angular 10 support
I got this error when i upgraded to angular 10

> [ng] node_modules/@angular/fire/firestore/firestore.module.d.ts:7:74 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).
[ng] 7     static enablePersistence(persistenceSettings?: PersistenceSettings): ModuleWithProviders;

here is the link to the  [Angular migration doc](https://next.angular.io/guide/migration-module-with-providers) for this issue

### PR DESCRIPTION
**Pull request by amayvs**
Resolves #187

### CODE REVIEW

**Comment by blondie63** [comment]
So need to wait for next ionic-storage release ?

**Comment by blondie63** [comment]
I've tried to replace node_modules/@ionic/storage/index.d.ts with this fix but i've this err:
```
[ng] ERROR in node_modules/@ionic/storage/index.d.ts:13:96 - error TS1183: An implementation cannot be declared in ambient contexts.
[ng] 13   static forRoot(storageConfig: StorageConfig = null): ModuleWithProviders<IonicStorageModule> {
[ng]                                                                                                   ~
```

**Comment by amayvs** [comment]
@blondie63 That's the recommended solutions as per following:

`ModuleWithProviders` has had the generic type since Angular version 7, but it has been optional. This has compiled because the `metadata.json` files contained all the metadata. With Ivy, `metadata.json` files are no longer required, so the framework cannot assume that one with the necessary types has been provided. Instead, Ivy relies on the generic type for `ModuleWithProviders` to get the correct type information.

For this reason, Angular version 9 deprecates `ModuleWithProviders` without a generic type. Angular 10 removes the default generic type, making an explicit type required.

Ref: https://angular.io/guide/migration-module-with-providers


If that doesn't work for you, you can try `ModuleWithProviders<any>`

**Comment by blondie63** [comment]
Look err on my side..
ionic-storage-A10-iss

**Comment by amayvs** [comment]
@blondie63 That's a declaration file, you should not add implementation in there.

**Comment by amayvs** [comment]
@adamdbradley @perrygovier Tagging since you were the last two to make commits to this repo. 

Is this repo still active? Who is maintaining it?

**Comment by blondie63** [comment]
Maybe Ionic Team only maintaining enterprise versions..
To test this fix i took the code from here: https://github.com/ionic-team/ionic-storage/pull/191/commits/882a868c2bead35f7ee3ffab9bdfcb50aeab202c
But it does'nt work :(

**Comment by amayvs** [comment]
@blondie63 You cannot put implementation in a declaration file. Please understand the difference. 

Revert `node_modules/@ionic/storage/index.d.ts` file to it's original content and replace `ModuleWithProviders` with `ModuleWithProviders<IonicStorageModule> `

If you're unable to resolve the issue, please avoid crowding the comments of this PR. It'll make it harder for the maintainers to quickly merge this PR (if they do).

**Pull request merged**
